definitions:
  main.ResponseError:
    properties:
      error:
        type: string
    type: object
  timestamppb.Timestamp:
    properties:
      nanos:
        description: |-
          Non-negative fractions of a second at nanosecond resolution. Negative
          second values with fractions must still have non-negative nanos values
          that count forward in time. Must be from 0 to 999,999,999
          inclusive.
        type: integer
      seconds:
        description: |-
          Represents seconds of UTC time since Unix epoch
          1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
          9999-12-31T23:59:59Z inclusive.
        type: integer
    type: object
  v1.QueryEventByBlockRangeRequest:
    properties:
      end:
        type: integer
      event:
        type: string
      start:
        type: integer
    type: object
  v1.QueryEventByBlockRangeResponseEvent:
    properties:
      blockId:
        type: integer
      eventID:
        type: string
      index:
        type: integer
      timestamp:
        $ref: '#/definitions/timestamppb.Timestamp'
      transactionId:
        type: string
      transactionIndex:
        type: integer
      type:
        type: string
      values:
        items:
          $ref: '#/definitions/v1.QueryEventByBlockRangeResponseValue'
        type: array
    type: object
  v1.QueryEventByBlockRangeResponseValue:
    properties:
      name:
        type: string
      value:
        type: string
    type: object
  v1.QueryLatestBlockHeightResponse:
    properties:
      latestBlockHeight:
        type: integer
    type: object
  v1.VersionResponse:
    properties:
      backendMode:
        type: string
      version:
        type: string
    type: object
host: localhost:8989
info:
  contact: {}
  description: flow-event-fetcher interface documentation
  title: flow-event-fetcher API
  version: 1.0.1
paths:
  /queryEventByBlockRange:
    post:
      consumes:
      - application/json
      description: queries event by block range
      parameters:
      - description: data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/v1.QueryEventByBlockRangeRequest'
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/v1.QueryEventByBlockRangeResponseEvent'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.ResponseError'
      summary: queries event by block range
      tags:
      - flow-event-fetcher
  /queryLatestBlockHeight:
    get:
      consumes:
      - application/json
      description: queries the latest block height
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.QueryLatestBlockHeightResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.ResponseError'
      summary: queries the latest block height
      tags:
      - flow-event-fetcher
  /syncSpork:
    get:
      consumes:
      - application/json
      description: sync spork
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.QueryLatestBlockHeightResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.ResponseError'
      summary: sync spork
      tags:
      - flow-event-fetcher
  /version:
    get:
      consumes:
      - application/json
      description: get version
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.VersionResponse'
      summary: get version
      tags:
      - flow-event-fetcher
swagger: "2.0"
